- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    LARAVEL_PROJECT_ROOT: "/var/www/trantech_staging/trantech"
    WEBSERVER_USER: "www-data"
    WEBSERVER_GROUP: "www-data"
    UBUNTU_USER: "root"
  tasks:
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
