- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    LARAVEL_PROJECT_ROOT: "/var/www/trantech_staging/trantech"
    WEBSERVER_USER: "www-data"
    WEBSERVER_GROUP: "www-data"
    UBUNTU_USER: "root"
  tasks:
    - name: "Enable mod_write"
      command: a2enmod rewrite
    - name: "Restart apache2 server"
      command: systemctl restart apache2
