- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    LARAVEL_PROJECT_ROOT: "/var/www/trantech_staging/trantech"
    WEBSERVER_USER: "www-data"
    WEBSERVER_GROUP: "www-data"
    UBUNTU_USER: "root"
  tasks:
    - name: "chown the root directory:"
      command: chown -R {{WEBSERVER_USER}}:{{WEBSERVER_GROUP}} {{LARAVEL_PROJECT_ROOT}}
    - name: "Grant FTP for uploading and working with files"
      command: usermod -a -G {{WEBSERVER_USER}} {{UBUNTU_USER}}
    - name: "Set file permission to 644"
      command: find {{LARAVEL_PROJECT_ROOT}} -type f -exec chmod 644 {} \;
    - name: "Set folder permission to 755"
      command: find {{LARAVEL_PROJECT_ROOT}} -type d -exec chmod 755 {} \;
