- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Adds Python MySQL support on Debian/Ubuntu
      apt: pkg="python-mysqldb" state=present
      when: ansible_os_family == 'Debian'

    - name: Adds Python MySQL support on RedHat/CentOS
      yum: name=MySQL-python state=present
      when: ansible_os_family == 'RedHat'

    - name: Sets the root password 
      mysql_user: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" user=root password="{{ MYSQL_ROOT_PWD }}" host=localhost

    - name: Deletes anonymous MySQL server user for ansible_fqdn
      mysql_user: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" user="" host="{{ ansible_fqdn }}" state="absent"

    - name: Deletes anonymous MySQL server user for localhost
      mysql_user: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" user="" state="absent"

    - name: Secures the MySQL root user for IPV6 localhost (::1)
      mysql_user: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" user="root" password="{{ MYSQL_ROOT_PWD }}" host="::1"

    - name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
      mysql_user: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" user="root" password="{{ MYSQL_ROOT_PWD }}" host="127.0.0.1"

    - name: Secures the MySQL root user for localhost domain (localhost)
      mysql_user: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" user="root" password="{{ MYSQL_ROOT_PWD }}" host="localhost"

    - name: Secures the MySQL root user for server_hostname domain
      mysql_user: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" user="root" password="{{ MYSQL_ROOT_PWD }}" host="{{ ansible_fqdn }}"

    - name: Removes the MySQL test database
      mysql_db: login_user="root" login_password="{{MYSQL_ROOT_PWD}}" db=test state=absent
