- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    PHP_VER: '7.2'
  tasks:
    - name: install php mod packages
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
        - php-bz2
        - php-gd
        - php-curl
        - php-gettext
        - php-mbstring
        - php-mysql
        - php-zip

    - name: Enable modules in php.ini
      lineinfile:
        path: /etc/php/{{PHP_VER}}/apache2/php.ini
        regexp: ";extension={{ item }}"
        line: "extension={{ item }}"
        state: present
        backrefs: yes
      loop:
        - bz2
        - curl
        - fileinfo
        - gd2
        - mbstring
        - exif
        - pdo_mysql

    - name: Set php max_execution_time
      lineinfile:
        path: /etc/php/{{PHP_VER}}/apache2/php.ini
        regexp: '^max_execution_time'
        line: 'max_execution_time=120'
        state: present
        backrefs: yes

    - name: Set php memory_limit
      lineinfile:
        path: /etc/php/{{PHP_VER}}/apache2/php.ini
        regexp: '^memory_limit'
        line: 'memory_limit=512M'
        state: present
        backrefs: yes

    - name: Set php max_file_uploads
      lineinfile:
        path: /etc/php/{{PHP_VER}}/apache2/php.ini
        regexp: '^max_file_uploads'
        line: 'max_file_uploads=20'
        state: present
        backrefs: yes

    - name: Set php post_max_size
      lineinfile:
        path: /etc/php/{{PHP_VER}}/apache2/php.ini
        regexp: '^post_max_size'
        line: 'post_max_size=200M'
        state: present
        backrefs: yes

    - name: Set php upload_max_filesize
      lineinfile:
        path: /etc/php/{{PHP_VER}}/apache2/php.ini
        regexp: '^upload_max_filesize'
        line: 'upload_max_filesize=200M'
        state: present
        backrefs: yes

    - name: "Restart apache2"
      command: systemctl restart apache2
