- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    WORKER_LOG: "/var/www/trantech_production/trantech/storage/logs/worker.log"
    WORKER_NAME: "laravel-worker"
    ARTISAN: "/var/www/trantech_production/trantech/artisan"
    WEBSERVER_USER: "www-data"
    WEBSERVER_GROUP: "www-data"
    UBUNTU_USER: "root"
    SUPERVISOR_CONF_PATH: "/etc/supervisor/conf.d"
  tasks:
    - name: Install supervisor package
      apt:
        name: supervisor

    - name: Make sure conf directory exist
      file:
        path: "{{SUPERVISOR_CONF_PATH}}"
        state: directory

    - name: "Create {{WORKER_NAME}} conf"
      template:
        src: ./files/supervisor-conf/supervisor-worker-template.conf
        dest: "{{SUPERVISOR_CONF_PATH}}/trantech-production-worker.conf"

    - name: Reread supervisor conf
      shell: supervisorctl reread

    - name: Update supervisor
      shell: supervisorctl update

    - name: Start laravel worker
      shell: "supervisorctl start {{WORKER_NAME}}"
