- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    PHP_VER: '7.2'
    DOCUMENT_ROOT: "/var/www/trantech_staging/public"
    DIRECTORY: "/var/www/trantech_staging/public/"
    ALIAS_ROUTE: "/staging"
    WEBSERVER_USER: "www-data"
    WEBSERVER_GROUP: "www-data"
    UBUNTU_USER: "root"
    HTTP_PORT: 80
    DOMAIN: "trantechsecurity.com.au"
  tasks:

    - name: Make sure trantech-staging.conf is disabled
      command: a2dissite trantech-staging
      args:
        removes: /etc/apache2/sites-enabled/trantech-staging.conf

    - name: Make sure default conf site is disabled
      command: a2dissite 000-default
      args:
        removes: /etc/apache2/sites-enabled/000-default.conf

    - name: Create new site conf for trantech_staging
      template: src=./files/virtual-host.conf dest=/etc/apache2/sites-available/trantech-staging.conf

    - name: Enable trantech-staging.conf and restart apache2
      command: a2ensite trantech-staging
      args:
        creates: /etc/apache2/sites-enabled/trantech-staging.conf
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

